Show OCR options to non-premium users
MuckRock/documentcloud-frontend pull request #119
Opened 2023-03-30 14:16 UTC by eyeseast

<img width="821" alt="Screenshot 2023-03-29 at 3 29 04 PM" src="https://user-images.githubusercontent.com/25778/228865337-25807823-1fee-40c2-8fa6-ef9520a3fdcd.png">
<img width="816" alt="Screenshot 2023-03-29 at 3 29 14 PM" src="https://user-images.githubusercontent.com/25778/228865347-3b99d997-c782-4b5f-bc83-6036bb76f69e.png">

2023-03-30 15:25 UTC, jimkang requested changes
Other than the concerns I had about nothing showing up in the language control in Firefox (which is caused by Firefox's datalist implementation as you said), I think this mostly looks good.

There are some simplification changes that I think would help with maintainability, but it's possible I'm actually misunderstanding the code. If that's the case just let me know!

2023-03-30 15:25 UTC, jimkang commented on src/pages/app/Paginator.svelte
> -  import { simplePlural } from "@/util/string";
Always great to see dead code removed!

2023-03-30 15:39 UTC, eyeseast commented on src/common/Select.svelte
> +  $: valueToName = options.reduce((m, opt) => {
It's not. Thought I'd need it but haven't yet. Might just take it out.

2023-03-30 16:37 UTC, jimkang commented on src/common/Select.svelte
> +  }, new Map());
Ah, OK. Maybe a comment explaining that this Map is for finding out if an option is selected and only for that would help.

2023-04-10 18:10 UTC, jimkang approved these changes
Latest commit looks good!

2023-04-10 18:11 UTC, merged